[workspace]
resolver = "2"
members = [
    "crates/oura-cli",
    "crates/oura-ffi",
    "crates/oura-core",
    "crates/oura-summary",
    "crates/oura-dna",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/Th0rgal/open_health"

[profile.release]
lto = true
strip = false

[patch."https://github.com/Th0rgal/open_oura"]
oura-store = { path = "vendor/oura-store" }
